pool:
  vmImage: 'Ubuntu 16.04'

trigger:
  branches:
    include:
    - master
    - feature/*
    - bug/*

variables:
  imageName: 'rapido-build-web'
  major: 0
  minor: 0
  patch: 1

pr:
  branches:
    include:
    - master

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'

- script: |
    pip install --upgrade pip
    pip install setuptools
    pip install awscli
  displayName: 'Environment Preperation'

- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: install

- script: |
    aws s3 cp s3://rapido-build-secrets-bucket/environment.staging.ts ./src/environment/environment.staging.ts
    aws s3 cp s3://rapido-build-secrets-bucket/environment.prod.ts ./src/environment/environment.prod.ts
  env:
    AWS_ACCESS_KEY_ID: $(accessKeyId)
    AWS_SECRET_ACCESS_KEY: $(secretAccessKey)
  displayName: 'Fetch secrets'

- task: Npm@1
  displayName: 'npm test'
  inputs:
    command: custom
    customCommand: 'test'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/TESTS-*.xml'
    testRunTitle: 'Rapidobuild test results'
  condition: succeededOrFailed()

- task: PublishCodeCoverageResults@1
  displayName: 'Publishing code coverage'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/rapido-web/index.html'
    reportDirectory: '$(System.DefaultWorkingDirectory)/coverage'

- task: Npm@1
  displayName: 'Prodbuild'
  inputs:
    command: custom
    customCommand: 'prodbuild'

- script: |
    docker build -t $DOCKER_REPO/$(imageName):v$(major).$(minor).$(patch) .
  env:
    DOCKER_REPO: $(dockerRepo)
  displayName: 'Build docker image and tag it'

- script: |
    docker login -u $(dockerId) -p $DOCKER_PASSWORD
    docker push $DOCKER_REPO/$(imageName):v$(major).$(minor).$(patch)
    docker tag $DOCKER_REPO/$(imageName):v$(major).$(minor).$(patch) $DOCKER_REPO/$(imageName):latest
    docker push $DOCKER_REPO/$(imageName):latest
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  env:
    AWS_ACCESS_KEY_ID: $(accessKeyId)
    AWS_SECRET_ACCESS_KEY: $(secretAccessKey)
    DOCKER_REPO: $(dockerRepo)
  displayName: 'Push Docker image'

