pool:
  vmImage: 'Ubuntu 16.04'

trigger:
  branches:
    include:
    - master
    - feature/*
    - bug/*

variables:
  imageName: 'rapido-web'
  major: 0
  minor: 0
  patch: 2

pr:
  branches:
    include:
    - master

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: 3.6
    architecture: 'x64'

- script: |
    pip install awscli
  displayName: 'Environment Preperation'

- script: |
    rm -rf ./src/environments/environment.ts
    aws s3 cp s3://rapido-build-secrets-bucket/environment.staging.ts ./src/environments/environment.staging.ts
    aws s3 cp s3://rapido-build-secrets-bucket/environment.prod.ts ./src/environments/environment.prod.ts
    aws s3 cp s3://rapido-build-secrets-bucket/environment.prod.ts ./src/environments/environment.ts
  env:
    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
  displayName: 'Fetch secrets from AWS and format'

- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Configuring the node tool'

- task: Npm@1
  displayName: 'Install all node modules'
  inputs:
    command: install

- script: |
    npm run testheadless
  displayName: 'Running tests'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/TESTS-*.xml'
    testRunTitle: 'Rapidobuild test results'
  condition: succeededOrFailed()

- task: PublishCodeCoverageResults@1
  displayName: 'Publishing code coverage'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/rapido-web/index.html'
    reportDirectory: '$(System.DefaultWorkingDirectory)/coverage/rapido-web'

- script: |
    npm run prodbuild
  displayName: 'Prod build'

- script: |
    docker build -t $DOCKER_REPO/$(imageName):v$(major).$(minor).$(patch) .
  env:
    DOCKER_REPO: $(DOCKER_REPO)
  displayName: 'Build docker image and tag it'

- script: |
    eval $(aws ecr get-login --no-include-email --region eu-west-2)
    docker push $DOCKER_REPO/$(imageName):v$(major).$(minor).$(patch)
    docker tag $DOCKER_REPO/$(imageName):v$(major).$(minor).$(patch) $DOCKER_REPO/$(imageName):latest
    docker push $DOCKER_REPO/$(imageName):latest
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  env:
    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
    DOCKER_REPO: $(DOCKER_REPO)
  displayName: 'Publish docker image to ECR'

- script: |
    aws s3 cp ${PWD}/dist/rapido-web/. s3://$DEV_RAPIDO_BUILD_S3_BUCKET --recursive
  condition: eq(variables['Build.Reason'], 'PullRequest')
  env:
    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
    DOCKER_REPO: $(DOCKER_REPO)
    DEV_RAPIDO_BUILD_S3_BUCKET: $(DEV_RAPIDO_BUILD_S3_BUCKET)
  displayName: 'Deploying distribution to dev environment'

- script: |
    aws s3 cp ${PWD}/dist/rapido-web/. s3://$PROD_RAPIDO_BUILD_S3_BUCKET --recursive
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  env:
    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
    DOCKER_REPO: $(DOCKER_REPO)
    PROD_RAPIDO_BUILD_S3_BUCKET: $(DEV_RAPIDO_BUILD_S3_BUCKET) # TODO: Change it PROD_RAPIDO_BUILD_S3_BUCKET when going live
  displayName: 'Deploying distribution to prod environment'
